### ISSUE TITLE
구글API 디버그용 키 없어요 

### ISSUE THREAD

**Issue by ykc415** [droidknights/DroidKnights-Festival-2019-flutter#23]
> E/flutter ( 7838): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml, null)

디버그 키 올려주세요 ㅠㅠ

**Comment by Jiyoung9310** [comment]
추가했습니당

**Comment by Jiyoung9310** [comment]
#53
