### ISSUE TITLE
Missing google-service.json

### ISSUE THREAD

**Issue by neulbo27** [droidknights/DroidKnights-Festival-2019-flutter#56]
#53 pull request를 통해 추가된 Google services, Google API 키 관련해 빌드 오류가 발생하고 있습니다.
google-services.json 파일이 누락되어서 빌드가 안되고 있는 것으로 보입니다.
아래 안드로이드 gradle 빌드 오류로그를 첨부해드리니 확인 후 추가, 수정 부탁드립니다.

>FAILURE: Build failed with an exception.
>
> What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/src/nullnull/debug/google-services.json
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/src/debug/nullnull/google-services.json
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/src/nullnull/google-services.json
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/src/debug/google-services.json
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/src/nullnullDebug/google-services.json
  /Users/.../DroidKnights-Festival-2019-flutter/android/app/google-services.json
>
 >Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
>Get more help at https://help.gradle.org
>
>BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by neulbo27** [comment]
iOS도 동일한 증상이 발생되어 빌드 로그 첨부드리니 확인 부탁드립니다.
>=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Runner" target.
>
>    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/Downloads/GoogleService-Info.plist:0: error: reading data: The file “GoogleService-Info.plist” couldn’t be opened because there is no such file.

**Comment by Jiyoung9310** [comment]
#58  파일 추가했는데 pull 받아보시고 확인해주세요..!!

**Comment by neulbo27** [comment]
정상적으로 빌드 되는 거 확인했습니다. 고맙습니다!
