### ISSUE TITLE
Await only futures 라는 경고가 뜨네요 

### ISSUE THREAD

**Issue by ykc415** [droidknights/DroidKnights-Festival-2019-flutter#71]
https://github.com/droidknights/DroidKnights-Festival-2019-flutter/blob/ba0495a7c9f4cd3e240853fd97ff195ba2e810a5/lib/bloc/schedule_like_bloc.dart#L29

https://github.com/droidknights/DroidKnights-Festival-2019-flutter/blob/ba0495a7c9f4cd3e240853fd97ff195ba2e810a5/lib/bloc/schedule_like_bloc.dart#L35

@chinapoopoo

SharedPreferences의 setString 은 내부적으로 안드로이드에서 비동기(SharedPreference.Editor의 apply)로 처리하지만 Future을 리턴하진 않네요 
await 대신 밑에서 commit() 을 불러야할것 같아요

**Comment by blue-marqvision** [comment]
수정해서 리퀘스트 날리겠습니다!
감사합니다 :)
